image: Visual Studio 2019

platform:
  - x64

# Test against these versions of Node.js.
environment:
  matrix:
  # node.js
    - nodejs_version: "12"
    - nodejs_version: "14"

matrix:
  fast_finish: true

install:
  - ps: Install-Product node $env:nodejs_version $env:platform

build: off

skip_commits:
  files:
    - '**/*.md'

test_script:
  - ps: node --version
  - ps: npm --version
  - ps: npm config set loglevel silent
  # NPM prefix should be writable by current user.
  - ps: npm config set prefix "$home\\.npm-prefix"
  - ps: $env:Path += ";$home\\.npm-prefix\\"
  - ps: npm install -g elm@latest-0.19.1 elm-test@latest-0.19.1
  - ps: npm install
  - ps: npm link
  - ps: npm run test
